apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: kompose -f ../../compose/compose-dev.yaml convert
    kompose.version: 1.34.0 (HEAD)
  labels:
    io.kompose.service: kafka
  name: kafka
spec:
  type: ClusterIP
  selector:
    io.kompose.service: kafka
  ports:
    - name: "29092"
      port: 29092
      targetPort: 29092
    - name: "9092"
      port: 9092
      targetPort: 9092
    - name: "29093"
      port: 9093
      targetPort: 9093
