CREATE TABLE confirmation_tokens
(
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    token        VARCHAR(255),
    user_id      BIGINT                                  NOT NULL,
    created_at   TIMESTAMP WITHOUT TIME ZONE,
    expires_at   TIMESTAMP WITHOUT TIME ZONE,
    confirmed_at TIMESTAMP WITHOUT TIME ZONE,
    CONSTRAINT pk_confirmation_tokens PRIMARY KEY (id)
);

CREATE TABLE tasks
(
    id                 BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    header             VARCHAR(255),
    description        VARCHAR(255),
    owner_id           BIGINT                                  NOT NULL,
    deadline_timestamp TIMESTAMP WITHOUT TIME ZONE,
    done_timestamp     TIMESTAMP WITHOUT TIME ZONE,
    CONSTRAINT pk_tasks PRIMARY KEY (id)
);

CREATE TABLE users
(
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    email         VARCHAR(320),
    password      VARCHAR(255),
    is_subscribed BOOLEAN DEFAULT FALSE                   NOT NULL,
    enabled       BOOLEAN DEFAULT FALSE,
    CONSTRAINT pk_users PRIMARY KEY (id)
);

ALTER TABLE confirmation_tokens
    ADD CONSTRAINT uc_confirmation_tokens_user UNIQUE (user_id);

ALTER TABLE users
    ADD CONSTRAINT uc_users_email UNIQUE (email);

ALTER TABLE confirmation_tokens
    ADD CONSTRAINT FK_CONFIRMATION_TOKENS_ON_USER FOREIGN KEY (user_id) REFERENCES users (id);

ALTER TABLE tasks
    ADD CONSTRAINT FK_TASKS_ON_OWNER FOREIGN KEY (owner_id) REFERENCES users (id);